#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# Masoud Tunnel Manager (v3.1 - Fixed)
# Ubuntu 22.04
#
# Features:
#  - Correct multiline env (systemd-friendly)
#  - Keys stored under /etc/masoud-tunnels/keys (ProtectHome safe)
#  - known_hosts writable via ReadWritePaths
#  - Remote Bootstrap (run from IRAN side):
#     * auto-generate .pub if missing
#     * ssh-copy-id (password once) to install key on remote
#     * Enable PermitTunnel yes + restart ssh on remote
#     * Install remote tun0 agent (auto IP/MTU setup)
#  - Service Manager:
#     * list/select masoud-* services and manage start/stop/restart/logs/remove
#
# Notes:
#  - Option 4 is for running bootstrap FROM this machine to a remote host.
#    In your setup, run it on IRAN server (client side), not on the foreign server.
# ==========================================================

RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[1;33m'
CYN=$'\033[0;36m'
NC=$'\033[0m'

BASE_DIR="/etc/masoud-tunnels"
KEY_DIR="${BASE_DIR}/keys"
KNOWN_HOSTS="${BASE_DIR}/known_hosts"
UNIT_DIR="/etc/systemd/system"

require_root() { [[ $EUID -eq 0 ]] || { echo "${RED}Run as root (sudo).${NC}"; exit 1; }; }

prompt() {
  local __var="$1" __text="$2" __default="${3:-}"
  local __val=""
  if [[ -n "$__default" ]]; then
    read -r -p "$__text [$__default]: " __val
    __val="${__val:-$__default}"
  else
    read -r -p "$__text: " __val
  fi
  printf -v "$__var" "%s" "$__val"
}

yesno() {
  local __var="$1" __text="$2" __default="${3:-y}"
  local __ans=""
  read -r -p "$__text (y/n) [$__default]: " __ans
  __ans="${__ans:-$__default}"
  __ans="$(echo "$__ans" | tr '[:upper:]' '[:lower:]')"
  if [[ "$__ans" == "y" || "$__ans" == "yes" ]]; then
    printf -v "$__var" "yes"
  else
    printf -v "$__var" "no"
  fi
}

install_deps() {
  echo "${CYN}Installing dependencies...${NC}"
  apt-get update -y
  apt-get install -y autossh openssh-client openssh-server iproute2 curl
  mkdir -p "$BASE_DIR" "$KEY_DIR"
  chmod 700 "$BASE_DIR" "$KEY_DIR"
  touch "$KNOWN_HOSTS"
  chmod 600 "$KNOWN_HOSTS"
}

write_env() {
  local env_path="$1"; shift
  {
    echo "# Generated by masoud-tunnel-manager"
    for kv in "$@"; do
      echo "$kv"
    done
  } > "$env_path"
  chmod 600 "$env_path"
}

ensure_key() {
  local key_path="$1"
  if [[ -f "$key_path" ]]; then
    chmod 600 "$key_path" 2>/dev/null || true
    # ensure pub exists too
    if [[ ! -f "${key_path}.pub" ]]; then
      ssh-keygen -y -f "$key_path" > "${key_path}.pub"
      chmod 644 "${key_path}.pub"
    fi
    return 0
  fi

  echo "${YLW}No SSH key at ${key_path}.${NC}"
  yesno GEN "Generate ED25519 key now?" "y"
  [[ "$GEN" == "yes" ]] || { echo "${RED}Need SSH key to continue.${NC}"; exit 1; }

  mkdir -p "$(dirname "$key_path")"
  ssh-keygen -t ed25519 -N "" -f "$key_path" -C "masoud-tunnel-manager"
  chmod 600 "$key_path"
  chmod 644 "${key_path}.pub"

  echo
  echo "${CYN}Public key:${NC}"
  cat "${key_path}.pub"
  echo
}

parse_ports_to_list() {
  local in="$1"
  local out=()
  IFS=',' read -r -a parts <<< "$in"
  for p in "${parts[@]}"; do
    p="$(echo "$p" | xargs)"
    [[ -z "$p" ]] && continue
    if [[ "$p" =~ ^([0-9]{1,5})-([0-9]{1,5})$ ]]; then
      local a="${BASH_REMATCH[1]}" b="${BASH_REMATCH[2]}"
      (( a > b )) && { local t="$a"; a="$b"; b="$t"; }
      for ((i=a;i<=b;i++)); do out+=("$i"); done
    elif [[ "$p" =~ ^[0-9]{1,5}$ ]]; then
      out+=("$p")
    else
      echo "${RED}Invalid port token: '$p'${NC}" >&2
      return 1
    fi
  done
  printf "%s\n" "${out[@]}"
}

build_L_args_same_ports() {
  local bind_host="$1" target_host="$2" ports_csv="$3"
  local ports; mapfile -t ports < <(parse_ports_to_list "$ports_csv")
  local args=()
  for port in "${ports[@]}"; do
    args+=("-L" "${bind_host}:${port}:${target_host}:${port}")
  done
  local joined=""
  for a in "${args[@]}"; do joined+=$(printf " %q" "$a"); done
  echo "$joined"
}

create_unit_tun_local() {
  local svc="$1" env_path="$2"

  cat > "${UNIT_DIR}/${svc}.service" <<EOF
[Unit]
Description=Masoud SSH-TUN (${svc})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${env_path}

ExecStart=/usr/bin/autossh \\
  -M 0 \\
  -N \\
  -o "ExitOnForwardFailure=yes" \\
  -o "ConnectTimeout=\${CONNECT_TIMEOUT}" \\
  -o "ServerAliveInterval=\${SERVER_ALIVE_INTERVAL}" \\
  -o "ServerAliveCountMax=\${SERVER_ALIVE_COUNTMAX}" \\
  -o "StrictHostKeyChecking=\${STRICT_HOST_KEY_CHECKING}" \\
  -o "UserKnownHostsFile=\${KNOWN_HOSTS_FILE}" \\
  -o "Compression=\${COMPRESSION}" \\
  -o "Ciphers=\${CIPHERS}" \\
  -o "Tunnel=point-to-point" \\
  -o "IdentitiesOnly=yes" \\
  -i "\${SSH_KEY}" \\
  -p "\${SSH_PORT}" \\
  -w 0:0 \\
  "\${SSH_USER}@\${SSH_HOST}"

ExecStartPost=/usr/local/bin/${svc}-postup "${env_path}"

Restart=always
RestartSec=2

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=${BASE_DIR}

[Install]
WantedBy=multi-user.target
EOF

  cat > "/usr/local/bin/${svc}-postup" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="$1"
# shellcheck disable=SC1090
source "$ENV_FILE"

for _ in {1..40}; do
  ip link show tun0 >/dev/null 2>&1 && break
  sleep 0.25
done
ip link show tun0 >/dev/null 2>&1 || exit 0

ip link set tun0 up || true
ip link set tun0 mtu "${TUN_MTU}" || true
ip addr flush dev tun0 || true
ip addr add "${LOCAL_TUN_IP}/32" peer "${REMOTE_TUN_IP}" dev tun0

if [[ -n "${ROUTE_SUBNET}" ]]; then
  ip route replace "${ROUTE_SUBNET}" via "${REMOTE_TUN_IP}" dev tun0
fi
EOF
  chmod +x "/usr/local/bin/${svc}-postup"
}

create_unit_forward_local() {
  local svc="$1" env_path="$2"
  cat > "${UNIT_DIR}/${svc}.service" <<EOF
[Unit]
Description=Masoud SSH Local-Forward (${svc})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${env_path}

ExecStart=/usr/bin/autossh \\
  -M 0 \\
  -N \\
  -o "ExitOnForwardFailure=yes" \\
  -o "ConnectTimeout=\${CONNECT_TIMEOUT}" \\
  -o "ServerAliveInterval=\${SERVER_ALIVE_INTERVAL}" \\
  -o "ServerAliveCountMax=\${SERVER_ALIVE_COUNTMAX}" \\
  -o "StrictHostKeyChecking=\${STRICT_HOST_KEY_CHECKING}" \\
  -o "UserKnownHostsFile=\${KNOWN_HOSTS_FILE}" \\
  -o "Compression=\${COMPRESSION}" \\
  -o "Ciphers=\${CIPHERS}" \\
  -o "IdentitiesOnly=yes" \\
  -i "\${SSH_KEY}" \\
  -p "\${SSH_PORT}" \\
  \${FORWARD_ARGS} \\
  "\${SSH_USER}@\${SSH_HOST}"

Restart=always
RestartSec=2

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=${BASE_DIR}

[Install]
WantedBy=multi-user.target
EOF
}

svc_enable_start() {
  local svc="$1"
  systemctl daemon-reload
  systemctl enable --now "${svc}.service"
  echo "${GRN}Started:${NC} ${svc}.service"
}

svc_remove_local() {
  local svc="$1"
  systemctl disable --now "$svc.service" 2>/dev/null || true
  rm -f "${UNIT_DIR}/${svc}.service"
  rm -f "${BASE_DIR}/${svc}.env"
  rm -f "/usr/local/bin/${svc}-postup" 2>/dev/null || true
  systemctl daemon-reload
  echo "${YLW}Removed local:${NC} $svc"
}

# -------- Remote Bootstrap (run from IRAN side) --------
remote_bootstrap() {
  local host="$1" user="$2" port="$3" key="$4" name="$5"
  local local_ip="$6" remote_ip="$7" mtu="$8"

  # Auto-generate .pub if missing
  if [[ ! -f "${key}.pub" && -f "$key" ]]; then
    ssh-keygen -y -f "$key" > "${key}.pub"
    chmod 644 "${key}.pub"
  fi

  local pub="${key}.pub"
  [[ -f "$pub" ]] || { echo "${RED}Public key not found: ${pub}${NC}"; return 1; }

  echo "${CYN}Step 1/3: Installing key on remote via ssh-copy-id (password may be asked once)...${NC}"
  ssh-copy-id -i "$pub" -p "$port" -o StrictHostKeyChecking=no "${user}@${host}"

  echo "${CYN}Step 2/3: Enabling PermitTunnel yes + restarting ssh on remote...${NC}"
  ssh -i "$key" -p "$port" -o StrictHostKeyChecking=no "${user}@${host}" bash -s <<'EOS'
set -euo pipefail
SSHD=/etc/ssh/sshd_config
cp -a "$SSHD" "${SSHD}.bak.$(date +%F_%H%M%S)" 2>/dev/null || true
if grep -qiE '^\s*PermitTunnel\s+' "$SSHD"; then
  sed -i 's/^\s*PermitTunnel\s\+.*/PermitTunnel yes/i' "$SSHD"
else
  echo "PermitTunnel yes" >> "$SSHD"
fi
systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true
EOS

  echo "${CYN}Step 3/3: Installing remote tun0 agent (auto IP/MTU setup)...${NC}"
  local r_local_ip="$remote_ip"
  local r_remote_ip="$local_ip"
  local agent="masoud-tun-agent-${name}"
  local agent_env="/etc/masoud-tunnels/${agent}.env"

  ssh -i "$key" -p "$port" -o StrictHostKeyChecking=no "${user}@${host}" bash -s -- "$agent" "$agent_env" "$r_local_ip" "$r_remote_ip" "$mtu" <<'EOS'
set -euo pipefail
AGENT="$1"
ENV_PATH="$2"
R_LOCAL_IP="$3"
R_REMOTE_IP="$4"
MTU="$5"

apt-get update -y >/dev/null 2>&1 || true
apt-get install -y iproute2 >/dev/null 2>&1 || true

mkdir -p /etc/masoud-tunnels
touch /etc/masoud-tunnels/known_hosts
chmod 600 /etc/masoud-tunnels/known_hosts

cat > "$ENV_PATH" <<EOF
R_LOCAL_IP=$R_LOCAL_IP
R_REMOTE_IP=$R_REMOTE_IP
TUN_MTU=$MTU
EOF
chmod 600 "$ENV_PATH"

cat > "/usr/local/bin/${AGENT}.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="$1"
# shellcheck disable=SC1090
source "$ENV_FILE"
while true; do
  if ip link show tun0 >/dev/null 2>&1; then
    ip link set tun0 up || true
    ip link set tun0 mtu "${TUN_MTU}" || true
    if ! ip -4 addr show dev tun0 | grep -q "${R_LOCAL_IP}"; then
      ip addr flush dev tun0 || true
      ip addr add "${R_LOCAL_IP}/32" peer "${R_REMOTE_IP}" dev tun0
    fi
  fi
  sleep 2
done
EOF
chmod +x "/usr/local/bin/${AGENT}.sh"

cat > "/etc/systemd/system/${AGENT}.service" <<EOF
[Unit]
Description=Masoud TUN Agent (${AGENT})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/${AGENT}.sh ${ENV_PATH}
Restart=always
RestartSec=2

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=/etc/masoud-tunnels

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "${AGENT}.service"
EOS

  echo "${GRN}Remote bootstrap completed.${NC}"
}

# -------- Service Manager --------
list_masoud_services() {
  systemctl list-unit-files --type=service | awk '{print $1}' | grep -E '^masoud-.*\.service$' || true
}

select_service() {
  local services
  mapfile -t services < <(list_masoud_services)
  if [[ ${#services[@]} -eq 0 ]]; then
    echo "${YLW}No masoud-* services found.${NC}"
    return 1
  fi

  echo
  echo "${CYN}Select a service:${NC}"
  local i=1
  for s in "${services[@]}"; do
    echo "  [$i] ${s}"
    ((i++))
  done
  echo "  [0] Cancel"
  read -r -p "Choice: " idx
  [[ "${idx:-}" =~ ^[0-9]+$ ]] || return 1
  if [[ "$idx" -eq 0 ]]; then return 1; fi
  if (( idx < 1 || idx > ${#services[@]} )); then return 1; fi
  SELECTED_SERVICE="${services[$((idx-1))]}"
  return 0
}

service_manager_menu() {
  while true; do
    echo
    echo "------------------------------"
    echo " Service Manager (masoud-*)"
    echo "------------------------------"
    echo "1) List services"
    echo "2) Start service"
    echo "3) Stop service"
    echo "4) Restart service"
    echo "5) Status service"
    echo "6) Logs service"
    echo "7) Remove service (local)"
    echo "0) Back"
    read -r -p "Select: " ch
    case "${ch:-}" in
      1) list_masoud_services | sed 's/^/ - /' ;;
      2) select_service && systemctl start "$SELECTED_SERVICE" && echo "${GRN}Started${NC} $SELECTED_SERVICE" ;;
      3) select_service && systemctl stop "$SELECTED_SERVICE" && echo "${YLW}Stopped${NC} $SELECTED_SERVICE" ;;
      4) select_service && systemctl restart "$SELECTED_SERVICE" && echo "${GRN}Restarted${NC} $SELECTED_SERVICE" ;;
      5) select_service && systemctl status "$SELECTED_SERVICE" --no-pager ;;
      6) select_service && journalctl -u "$SELECTED_SERVICE" -n 200 --no-pager ;;
      7)
        select_service || continue
        svc="${SELECTED_SERVICE%.service}"
        yesno CONF "Remove local service '$svc'?" "n"
        [[ "$CONF" == "yes" ]] && svc_remove_local "$svc"
        ;;
      0) break ;;
      *) echo "${RED}Invalid.${NC}" ;;
    esac
  done
}

menu() {
  cat <<'EOF'

==============================
 Masoud Tunnel Manager (v3.1)
==============================

1) Install dependencies
2) Create TUN tunnel (ssh -w)  + Optional Remote Bootstrap (key+PermitTunnel+agent)
3) Create Local Forward (-L)
4) Remote Bootstrap only (key+PermitTunnel+agent)   [Run on IRAN server]
5) Service Manager (list/select/start/stop/restart/logs/remove)
0) Exit
EOF
}

require_root

while true; do
  menu
  read -r -p "Select: " CH
  case "${CH:-}" in
    1)
      install_deps
      ;;
    2)
      install_deps

      prompt NAME "Tunnel name" "t1"
      svc="masoud-tun-${NAME}"

      prompt SSH_HOST "Destination SSH host/IP" ""
      prompt SSH_USER "Destination SSH user" "root"
      prompt SSH_PORT "Destination SSH port" "22"

      DEFAULT_KEY="${KEY_DIR}/${NAME}_ed25519"
      prompt SSH_KEY "SSH private key path" "$DEFAULT_KEY"
      ensure_key "$SSH_KEY"

      echo "${CYN}TUN settings:${NC}"
      prompt LOCAL_TUN_IP  "LOCAL tun IP (this server)"  "10.77.0.1"
      prompt REMOTE_TUN_IP "REMOTE tun IP (destination)" "10.77.0.2"
      prompt TUN_MTU "MTU" "1400"
      prompt ROUTE_SUBNET "Optional route subnet via tun (empty=none)" ""

      yesno COMP "Enable SSH compression?" "n"
      COMPRESSION=$([[ "$COMP" == "yes" ]] && echo "yes" || echo "no")

      yesno STRICT "StrictHostKeyChecking (yes=accept-new recommended)?" "y"
      STRICT_HOST_KEY_CHECKING=$([[ "$STRICT" == "yes" ]] && echo "accept-new" || echo "no")

      prompt CONNECT_TIMEOUT "ConnectTimeout" "10"
      prompt SERVER_ALIVE_INTERVAL "ServerAliveInterval" "20"
      prompt SERVER_ALIVE_COUNTMAX "ServerAliveCountMax" "3"
      prompt CIPHERS "Ciphers" "chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com"

      ssh-keyscan -H "$SSH_HOST" >> "$KNOWN_HOSTS" 2>/dev/null || true

      env_path="${BASE_DIR}/${svc}.env"
      write_env "$env_path" \
        "SSH_HOST=${SSH_HOST}" \
        "SSH_USER=${SSH_USER}" \
        "SSH_PORT=${SSH_PORT}" \
        "SSH_KEY=${SSH_KEY}" \
        "CONNECT_TIMEOUT=${CONNECT_TIMEOUT}" \
        "SERVER_ALIVE_INTERVAL=${SERVER_ALIVE_INTERVAL}" \
        "SERVER_ALIVE_COUNTMAX=${SERVER_ALIVE_COUNTMAX}" \
        "STRICT_HOST_KEY_CHECKING=${STRICT_HOST_KEY_CHECKING}" \
        "KNOWN_HOSTS_FILE=${KNOWN_HOSTS}" \
        "COMPRESSION=${COMPRESSION}" \
        "CIPHERS=${CIPHERS}" \
        "LOCAL_TUN_IP=${LOCAL_TUN_IP}" \
        "REMOTE_TUN_IP=${REMOTE_TUN_IP}" \
        "TUN_MTU=${TUN_MTU}" \
        "ROUTE_SUBNET=${ROUTE_SUBNET}"

      create_unit_tun_local "$svc" "$env_path"

      yesno BOOT "Remote Bootstrap now? (auto key install + PermitTunnel + remote agent)" "y"
      if [[ "$BOOT" == "yes" ]]; then
        remote_bootstrap "$SSH_HOST" "$SSH_USER" "$SSH_PORT" "$SSH_KEY" "$NAME" "$LOCAL_TUN_IP" "$REMOTE_TUN_IP" "$TUN_MTU"
      else
        echo "${YLW}Remote side must have PermitTunnel and tun0 IP configured, otherwise ping won't work.${NC}"
      fi

      svc_enable_start "$svc"
      echo "${CYN}Local check:${NC} ip addr show tun0 ; ping ${REMOTE_TUN_IP}"
      ;;
    3)
      install_deps

      prompt NAME "Forward name" "f1"
      svc="masoud-fwd-${NAME}"

      prompt SSH_HOST "Destination SSH host/IP" ""
      prompt SSH_USER "Destination SSH user" "root"
      prompt SSH_PORT "Destination SSH port" "22"

      DEFAULT_KEY="${KEY_DIR}/${NAME}_ed25519"
      prompt SSH_KEY "SSH private key path" "$DEFAULT_KEY"
      ensure_key "$SSH_KEY"

      echo "${CYN}Forward ports/ranges:${NC}"
      prompt PORTS "Ports (e.g. 2000,2088,2096 or 10000-10070)" "2000,2088,2096"
      prompt BIND_HOST "Local bind (127.0.0.1 or 0.0.0.0)" "0.0.0.0"
      prompt TARGET_HOST "Remote target host" "127.0.0.1"
      FORWARD_ARGS="$(build_L_args_same_ports "$BIND_HOST" "$TARGET_HOST" "$PORTS")"

      yesno COMP "Enable SSH compression?" "n"
      COMPRESSION=$([[ "$COMP" == "yes" ]] && echo "yes" || echo "no")

      yesno STRICT "StrictHostKeyChecking (yes=accept-new recommended)?" "y"
      STRICT_HOST_KEY_CHECKING=$([[ "$STRICT" == "yes" ]] && echo "accept-new" || echo "no")

      prompt CONNECT_TIMEOUT "ConnectTimeout" "10"
      prompt SERVER_ALIVE_INTERVAL "ServerAliveInterval" "20"
      prompt SERVER_ALIVE_COUNTMAX "ServerAliveCountMax" "3"
      prompt CIPHERS "Ciphers" "chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com"

      ssh-keyscan -H "$SSH_HOST" >> "$KNOWN_HOSTS" 2>/dev/null || true

      env_path="${BASE_DIR}/${svc}.env"
      write_env "$env_path" \
        "SSH_HOST=${SSH_HOST}" \
        "SSH_USER=${SSH_USER}" \
        "SSH_PORT=${SSH_PORT}" \
        "SSH_KEY=${SSH_KEY}" \
        "FORWARD_ARGS=${FORWARD_ARGS}" \
        "CONNECT_TIMEOUT=${CONNECT_TIMEOUT}" \
        "SERVER_ALIVE_INTERVAL=${SERVER_ALIVE_INTERVAL}" \
        "SERVER_ALIVE_COUNTMAX=${SERVER_ALIVE_COUNTMAX}" \
        "STRICT_HOST_KEY_CHECKING=${STRICT_HOST_KEY_CHECKING}" \
        "KNOWN_HOSTS_FILE=${KNOWN_HOSTS}" \
        "COMPRESSION=${COMPRESSION}" \
        "CIPHERS=${CIPHERS}"

      create_unit_forward_local "$svc" "$env_path"
      svc_enable_start "$svc"
      ;;
    4)
      install_deps
      prompt NAME "Tunnel name (for agent naming)" "t1"
      prompt SSH_HOST "Destination SSH host/IP" ""
      prompt SSH_USER "Destination SSH user" "root"
      prompt SSH_PORT "Destination SSH port" "22"
      DEFAULT_KEY="${KEY_DIR}/${NAME}_ed25519"
      prompt SSH_KEY "SSH private key path" "$DEFAULT_KEY"
      ensure_key "$SSH_KEY"
      prompt LOCAL_TUN_IP  "LOCAL tun IP (this server)"  "10.77.0.1"
      prompt REMOTE_TUN_IP "REMOTE tun IP (destination)" "10.77.0.2"
      prompt TUN_MTU "MTU" "1400"
      remote_bootstrap "$SSH_HOST" "$SSH_USER" "$SSH_PORT" "$SSH_KEY" "$NAME" "$LOCAL_TUN_IP" "$REMOTE_TUN_IP" "$TUN_MTU"
      ;;
    5)
      service_manager_menu
      ;;
    0) exit 0 ;;
    *) echo "${RED}Invalid.${NC}" ;;
  esac
done
