#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# Masoud Tunnel Manager
# Ubuntu 22.04
# Modes:
#   1) SSH TUN (ssh -w)  [one connection, low overhead]
#   2) SSH Local Forward (-L) [few ports/ranges]
# Features:
#   - Interactive menu
#   - systemd services
#   - autossh keepalive/reconnect
#   - add/remove/status/logs
# ==========================================================

RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[1;33m'
CYN=$'\033[0;36m'
NC=$'\033[0m'

BASE_DIR="/etc/masoud-tunnels"
UNIT_DIR="/etc/systemd/system"

require_root() { [[ $EUID -eq 0 ]] || { echo "${RED}Run as root (sudo).${NC}"; exit 1; }; }
have_cmd() { command -v "$1" >/dev/null 2>&1; }

install_deps() {
  echo "${CYN}Installing dependencies...${NC}"
  apt-get update -y
  apt-get install -y autossh openssh-client openssh-server iproute2
  mkdir -p "$BASE_DIR"
  chmod 700 "$BASE_DIR"
}

prompt() {
  local __var="$1" __text="$2" __default="${3:-}"
  local __val=""
  if [[ -n "$__default" ]]; then
    read -r -p "$__text [$__default]: " __val
    __val="${__val:-$__default}"
  else
    read -r -p "$__text: " __val
  fi
  printf -v "$__var" "%s" "$__val"
}

yesno() {
  local __var="$1" __text="$2" __default="${3:-y}"
  local __ans=""
  read -r -p "$__text (y/n) [$__default]: " __ans
  __ans="${__ans:-$__default}"
  __ans="$(echo "$__ans" | tr '[:upper:]' '[:lower:]')"
  if [[ "$__ans" == "y" || "$__ans" == "yes" ]]; then
    printf -v "$__var" "yes"
  else
    printf -v "$__var" "no"
  fi
}

ensure_key() {
  local key_path="$1"
  if [[ -f "$key_path" ]]; then
    chmod 600 "$key_path" 2>/dev/null || true
    return 0
  fi
  echo "${YLW}No SSH key at ${key_path}.${NC}"
  yesno GEN "Generate ED25519 key now?" "y"
  [[ "$GEN" == "yes" ]] || { echo "${RED}Need SSH key to continue.${NC}"; exit 1; }
  mkdir -p "$(dirname "$key_path")"
  ssh-keygen -t ed25519 -N "" -f "$key_path" -C "masoud-tunnel-manager"
  chmod 600 "$key_path"
  echo
  echo "${CYN}Public key (copy to destination ~/.ssh/authorized_keys):${NC}"
  cat "${key_path}.pub"
  echo
}

parse_ports_to_list() {
  local in="$1"
  local out=()
  IFS=',' read -r -a parts <<< "$in"
  for p in "${parts[@]}"; do
    p="$(echo "$p" | xargs)"
    [[ -z "$p" ]] && continue
    if [[ "$p" =~ ^([0-9]{1,5})-([0-9]{1,5})$ ]]; then
      local a="${BASH_REMATCH[1]}" b="${BASH_REMATCH[2]}"
      (( a > b )) && { local t="$a"; a="$b"; b="$t"; }
      for ((i=a;i<=b;i++)); do out+=("$i"); done
    elif [[ "$p" =~ ^[0-9]{1,5}$ ]]; then
      out+=("$p")
    else
      echo "${RED}Invalid port token: '$p'${NC}" >&2
      return 1
    fi
  done
  printf "%s\n" "${out[@]}"
}

write_env() {
  local env_path="$1"; shift
  cat > "$env_path" <<EOF
# Generated by masoud-tunnel-manager
$*
EOF
  chmod 600 "$env_path"
}

enable_permit_tunnel_on_this_server() {
  local sshd_cfg="/etc/ssh/sshd_config"
  cp -a "$sshd_cfg" "${sshd_cfg}.bak.$(date +%F_%H%M%S)" || true
  if grep -qiE '^\s*PermitTunnel\s+' "$sshd_cfg"; then
    sed -i 's/^\s*PermitTunnel\s\+.*/PermitTunnel yes/i' "$sshd_cfg"
  else
    echo "PermitTunnel yes" >> "$sshd_cfg"
  fi
  systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true
  echo "${GRN}PermitTunnel enabled on THIS server (sshd).${NC}"
}

create_unit_tun() {
  local svc="$1" env_path="$2"
  cat > "${UNIT_DIR}/${svc}.service" <<EOF
[Unit]
Description=Masoud SSH-TUN (${svc})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${env_path}
ExecStart=/usr/bin/autossh \\
  -M 0 \\
  -N \\
  -o "ExitOnForwardFailure=yes" \\
  -o "ConnectTimeout=\${CONNECT_TIMEOUT}" \\
  -o "ServerAliveInterval=\${SERVER_ALIVE_INTERVAL}" \\
  -o "ServerAliveCountMax=\${SERVER_ALIVE_COUNTMAX}" \\
  -o "StrictHostKeyChecking=\${STRICT_HOST_KEY_CHECKING}" \\
  -o "UserKnownHostsFile=\${KNOWN_HOSTS_FILE}" \\
  -o "Compression=\${COMPRESSION}" \\
  -o "Ciphers=\${CIPHERS}" \\
  -o "Tunnel=point-to-point" \\
  -o "IdentitiesOnly=yes" \\
  -i "\${SSH_KEY}" \\
  -p "\${SSH_PORT}" \\
  -w 0:0 \\
  "\${SSH_USER}@\${SSH_HOST}"

ExecStartPost=/usr/local/bin/${svc}-postup "${env_path}"

Restart=always
RestartSec=2

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF

  cat > "/usr/local/bin/${svc}-postup" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="$1"
# shellcheck disable=SC1090
source "$ENV_FILE"

# wait a bit for tun0 to appear
for _ in {1..20}; do
  ip link show tun0 >/dev/null 2>&1 && break
  sleep 0.2
done
ip link show tun0 >/dev/null 2>&1 || exit 0

ip link set tun0 up || true
ip link set tun0 mtu "${TUN_MTU}" || true
ip addr flush dev tun0 || true
ip addr add "${LOCAL_TUN_IP}/32" peer "${REMOTE_TUN_IP}" dev tun0

# Optional: route a subnet via tunnel (for private service networks)
if [[ -n "${ROUTE_SUBNET}" ]]; then
  ip route replace "${ROUTE_SUBNET}" via "${REMOTE_TUN_IP}" dev tun0
fi
EOF
  chmod +x "/usr/local/bin/${svc}-postup"
}

create_unit_local_forward() {
  local svc="$1" env_path="$2"
  cat > "${UNIT_DIR}/${svc}.service" <<EOF
[Unit]
Description=Masoud SSH Local-Forward (${svc})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${env_path}
ExecStart=/usr/bin/autossh \\
  -M 0 \\
  -N \\
  -o "ExitOnForwardFailure=yes" \\
  -o "ConnectTimeout=\${CONNECT_TIMEOUT}" \\
  -o "ServerAliveInterval=\${SERVER_ALIVE_INTERVAL}" \\
  -o "ServerAliveCountMax=\${SERVER_ALIVE_COUNTMAX}" \\
  -o "StrictHostKeyChecking=\${STRICT_HOST_KEY_CHECKING}" \\
  -o "UserKnownHostsFile=\${KNOWN_HOSTS_FILE}" \\
  -o "Compression=\${COMPRESSION}" \\
  -o "Ciphers=\${CIPHERS}" \\
  -o "IdentitiesOnly=yes" \\
  -i "\${SSH_KEY}" \\
  -p "\${SSH_PORT}" \\
  \${FORWARD_ARGS} \\
  "\${SSH_USER}@\${SSH_HOST}"
Restart=always
RestartSec=2

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true

[Install]
WantedBy=multi-user.target
EOF
}

build_L_args_same_ports() {
  local bind_host="$1" target_host="$2" ports_csv="$3"
  local ports; mapfile -t ports < <(parse_ports_to_list "$ports_csv")
  local args=()
  for port in "${ports[@]}"; do
    args+=("-L" "${bind_host}:${port}:${target_host}:${port}")
  done
  local joined=""
  for a in "${args[@]}"; do joined+=$(printf " %q" "$a"); done
  echo "$joined"
}

svc_enable_start() {
  local svc="$1"
  systemctl daemon-reload
  systemctl enable --now "${svc}.service"
  echo "${GRN}Started:${NC} ${svc}.service"
}

svc_status() { systemctl status "$1.service" --no-pager || true; }
svc_logs() { journalctl -u "$1.service" -n 150 --no-pager || true; }
svc_restart() { systemctl restart "$1.service"; }
svc_stop() { systemctl stop "$1.service" || true; }
svc_remove() {
  local svc="$1"
  systemctl disable --now "$svc.service" || true
  rm -f "${UNIT_DIR}/${svc}.service"
  rm -f "${BASE_DIR}/${svc}.env"
  rm -f "/usr/local/bin/${svc}-postup" 2>/dev/null || true
  systemctl daemon-reload
  echo "${YLW}Removed:${NC} $svc"
}

menu() {
  cat <<'EOF'

==============================
 Masoud Tunnel Manager
 Ubuntu 22.04 (TCP/SSH)
==============================

1) Install dependencies
2) Create TUN tunnel (ssh -w)  [recommended low overhead]
3) Create Local Forward (-L)   [few ports/ranges]
4) Enable PermitTunnel on THIS server (sshd)
5) Status
6) Logs
7) Restart
8) Stop
9) Remove
0) Exit
EOF
}

require_root

while true; do
  menu
  read -r -p "Select: " CH
  case "${CH:-}" in
    1)
      install_deps
      ;;
    2)
      install_deps
      prompt NAME "Tunnel name" "t1"
      svc="masoud-tun-${NAME}"

      prompt SSH_HOST "Destination SSH host/IP" ""
      prompt SSH_USER "Destination SSH user" "root"
      prompt SSH_PORT "Destination SSH port" "22"
      prompt SSH_KEY  "SSH private key path" "/root/.ssh/id_ed25519"
      ensure_key "$SSH_KEY"

      echo "${CYN}TUN settings:${NC}"
      prompt LOCAL_TUN_IP  "LOCAL tun IP (this server)"  "10.77.0.1"
      prompt REMOTE_TUN_IP "REMOTE tun IP (destination)" "10.77.0.2"
      prompt TUN_MTU "MTU" "1400"
      prompt ROUTE_SUBNET "Optional route subnet via tun (empty=none)" ""

      yesno COMP "Enable SSH compression?" "n"
      COMPRESSION=$([[ "$COMP" == "yes" ]] && echo "yes" || echo "no")

      prompt CONNECT_TIMEOUT "ConnectTimeout" "10"
      prompt SERVER_ALIVE_INTERVAL "ServerAliveInterval" "20"
      prompt SERVER_ALIVE_COUNTMAX "ServerAliveCountMax" "3"
      yesno STRICT "StrictHostKeyChecking?" "n"
      STRICT_HOST_KEY_CHECKING=$([[ "$STRICT" == "yes" ]] && echo "yes" || echo "no")
      KNOWN_HOSTS_FILE="${BASE_DIR}/known_hosts"
      prompt CIPHERS "Ciphers" "chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com"

      env_path="${BASE_DIR}/${svc}.env"
      write_env "$env_path" \
        "SSH_HOST=${SSH_HOST}" \
        "SSH_USER=${SSH_USER}" \
        "SSH_PORT=${SSH_PORT}" \
        "SSH_KEY=${SSH_KEY}" \
        "CONNECT_TIMEOUT=${CONNECT_TIMEOUT}" \
        "SERVER_ALIVE_INTERVAL=${SERVER_ALIVE_INTERVAL}" \
        "SERVER_ALIVE_COUNTMAX=${SERVER_ALIVE_COUNTMAX}" \
        "STRICT_HOST_KEY_CHECKING=${STRICT_HOST_KEY_CHECKING}" \
        "KNOWN_HOSTS_FILE=${KNOWN_HOSTS_FILE}" \
        "COMPRESSION=${COMPRESSION}" \
        "CIPHERS=${CIPHERS}" \
        "LOCAL_TUN_IP=${LOCAL_TUN_IP}" \
        "REMOTE_TUN_IP=${REMOTE_TUN_IP}" \
        "TUN_MTU=${TUN_MTU}" \
        "ROUTE_SUBNET=${ROUTE_SUBNET}"

      create_unit_tun "$svc" "$env_path"
      svc_enable_start "$svc"

      echo
      echo "${YLW}IMPORTANT:${NC} On destination server sshd must allow tunneling:"
      echo "  Run option 4 (Enable PermitTunnel) on destination server."
      ;;
    3)
      install_deps
      prompt NAME "Forward name" "f1"
      svc="masoud-fwd-${NAME}"

      prompt SSH_HOST "Destination SSH host/IP" ""
      prompt SSH_USER "Destination SSH user" "root"
      prompt SSH_PORT "Destination SSH port" "22"
      prompt SSH_KEY  "SSH private key path" "/root/.ssh/id_ed25519"
      ensure_key "$SSH_KEY"

      echo "${CYN}Forward ports/ranges (same port numbers):${NC}"
      prompt PORTS "Ports (e.g. 2000,2088,2096 or 10000-10070)" "2000,2088,2096"
      prompt BIND_HOST "Local bind (127.0.0.1 or 0.0.0.0)" "0.0.0.0"
      prompt TARGET_HOST "Remote target host" "127.0.0.1"

      FORWARD_ARGS="$(build_L_args_same_ports "$BIND_HOST" "$TARGET_HOST" "$PORTS")"

      yesno COMP "Enable SSH compression?" "n"
      COMPRESSION=$([[ "$COMP" == "yes" ]] && echo "yes" || echo "no")

      prompt CONNECT_TIMEOUT "ConnectTimeout" "10"
      prompt SERVER_ALIVE_INTERVAL "ServerAliveInterval" "20"
      prompt SERVER_ALIVE_COUNTMAX "ServerAliveCountMax" "3"
      yesno STRICT "StrictHostKeyChecking?" "n"
      STRICT_HOST_KEY_CHECKING=$([[ "$STRICT" == "yes" ]] && echo "yes" || echo "no")
      KNOWN_HOSTS_FILE="${BASE_DIR}/known_hosts"
      prompt CIPHERS "Ciphers" "chacha20-poly1305@openssh.com,aes128-gcm@openssh.com,aes256-gcm@openssh.com"

      env_path="${BASE_DIR}/${svc}.env"
      write_env "$env_path" \
        "SSH_HOST=${SSH_HOST}" \
        "SSH_USER=${SSH_USER}" \
        "SSH_PORT=${SSH_PORT}" \
        "SSH_KEY=${SSH_KEY}" \
        "FORWARD_ARGS=${FORWARD_ARGS}" \
        "CONNECT_TIMEOUT=${CONNECT_TIMEOUT}" \
        "SERVER_ALIVE_INTERVAL=${SERVER_ALIVE_INTERVAL}" \
        "SERVER_ALIVE_COUNTMAX=${SERVER_ALIVE_COUNTMAX}" \
        "STRICT_HOST_KEY_CHECKING=${STRICT_HOST_KEY_CHECKING}" \
        "KNOWN_HOSTS_FILE=${KNOWN_HOSTS_FILE}" \
        "COMPRESSION=${COMPRESSION}" \
        "CIPHERS=${CIPHERS}"

      create_unit_local_forward "$svc" "$env_path"
      svc_enable_start "$svc"
      ;;
    4)
      enable_permit_tunnel_on_this_server
      ;;
    5)
      prompt SVC "Service name (e.g. masoud-tun-t1)" ""
      svc_status "$SVC"
      ;;
    6)
      prompt SVC "Service name" ""
      svc_logs "$SVC"
      ;;
    7)
      prompt SVC "Service name" ""
      svc_restart "$SVC"
      svc_status "$SVC"
      ;;
    8)
      prompt SVC "Service name" ""
      svc_stop "$SVC"
      ;;
    9)
      prompt SVC "Service name" ""
      svc_remove "$SVC"
      ;;
    0) exit 0 ;;
    *) echo "${RED}Invalid.${NC}" ;;
  esac
done